image: mcr.microsoft.com/dotnet/core/sdk:3.0

before_script:
    - cd dev/src/HAL/ 
 
build:
    stage: build
    script:
        - dotnet build -c Release 
   
test:
    stage: test
    script:
        - dotnet test --no-restore

deploy:
    stage: deploy        
    script:
        - dotnet publish -c Release -o $CI_PROJECT_DIR/build/release
    artifacts:
        paths:
            - $CI_PROJECT_DIR/build/release